### ISSUE TITLE
deleted cuz you won't respond to dumb people like me

### ISSUE THREAD

**Issue by ghost** [xerub/separt#1]

**Comment by xerub** [comment]
Haha, sorry, but that's not true. It's just I missed it completely; you should’ve pinged me on twitter :)

**Comment by ghost** [comment]
Actually it’s not a issue, just asked here bc you never reply me on twitter: https://twitter.com/b1n4r1b01/status/1037387817037352961?s=20

**Comment by xerub** [comment]
That element you pointed to is the HMAC-SHA256: https://en.wikipedia.org/wiki/HMAC

**Comment by ghost** [comment]
Thanks for replying! So it means we can’t set a custom snon by loading a custom ART? (without any of your magic). Also ART doesn’t seems to be a thing on A9+ SEPs (I can be wrong) but if so then how is snon setup on those devices? Can you DM me on Twitter (no wen eta questions for sure)

**Comment by xerub** [comment]
You can't just load a custom ART because of HMAC-SHA. A9+ ART is there, but in a different place :)
